version: '3.13'

services:
  api-gateway-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_PERSIST_DIRECTORY=/chroma_db
      - DEBUG=true
    volumes:
      # Mount source code for hot reloading
      - ./app:/app
      - ./chroma_db:/chroma_db
      - ./.env:/.env
      # Exclude pycache
      - /app/app/__pycache__
    command: python -u run.py
    restart: unless-stopped
    networks:
      - agent-network
    stdin_open: true
    tty: true

networks:
  agent-network:
    driver: bridge